export const TABLE_CELL_ROLE_ID = 'ID'
export const TABLE_CELL_ROLE_STATIC = 'STATIC'
export const TABLE_CELL_ROLE_INPUT = 'INPUT'
export const TABLE_CELL_ROLE_TEXT_AREA = 'TEXT_AREA'
export const TABLE_CELL_ROLE_DATE = 'DATE'



export const TABLE_ROW_STATUS_EDIT = 'EDIT'
export const TABLE_ROW_STATUS_CREATED = 'CREATED'
export const TABLE_ROW_STATUS_STATIC = 'STATIC'
export const TABLE_ROW_STATUS_STATIC_DISABLED = 'STATIC_DISABLED'



export const TABLE_REDUCER_UPDATE = 'UPDATE'
export const TABLE_REDUCER_SAVE_ROW = 'SAVE_ROW'
export const TABLE_REDUCER_CREATE_ROW = 'CREATE_ROW'
export const TABLE_REDUCER_DELETE_ROW = 'DELETE_ROW'
export const TABLE_REDUCER_DELETE_CREATE_ROW = 'DELETE_CREATE_ROW'
